const translations = {
  en: {
    title: "Impressum",
    content: [
      "This website is a project developed to provide a wrapper around OpenAI&apos;s ChatGPT API. The content generated by this service is created by an AI model and is not manually reviewed or verified by us.",
      <span key="en-disclaimer">
        <strong>Disclaimer:</strong> We are not responsible for the content
        created by the AI model. The generated content may not always be
        accurate, complete, or up-to-date. Users should verify the information
        independently before relying on it.
      </span>,
      <span key="en-openai-disclaimer">
        For more information about the limitations and disclaimers related to
        OpenAI&apos;s services, please refer to OpenAI&apos;s official
        disclaimer:
        <a
          href="https://openai.com/policies/service-terms/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-500 hover:underline ml-1"
        >
          OpenAI Disclaimer
        </a>
        .
      </span>,
      <span key="en-contact-info">
        <strong>Contact Information:</strong>
        <br />
        Diego de Miguel
        <br />
        Sillemstraße 43
        <br />
        Hamburg, 20257
        <br />
        Email:{" "}
        <a
          href="mailto:diedemiguel@gmail.com"
          className="text-blue-500 hover:underline"
        >
          diedemiguel@gmail.com
        </a>
        <br />
      </span>,
    ],
    homeLink: "Home",
    language: "Language",
    english: "English",
    german: "Deutsch",
  },
  de: {
    title: "Impressum",
    content: [
      "Diese Website ist ein Projekt, das entwickelt wurde, um eine Wrapper um die ChatGPT-API von OpenAI bereitzustellen. Die von diesem Service generierten Inhalte werden von einem KI-Modell erstellt und nicht von uns manuell überprüft oder verifiziert.",
      <span key="de-haftungsausschluss">
        <strong>Haftungsausschluss:</strong> Wir sind nicht verantwortlich für
        die von dem KI-Modell erstellten Inhalte. Die generierten Inhalte sind
        möglicherweise nicht immer genau, vollständig oder aktuell. Benutzer
        sollten die Informationen unabhängig überprüfen, bevor sie sich darauf
        verlassen.
      </span>,
      <span key="de-openai-haftungsausschluss">
        Für weitere Informationen zu den Einschränkungen und
        Haftungsausschlüssen im Zusammenhang mit den Diensten von OpenAI
        verweisen wir auf den offiziellen Haftungsausschluss von OpenAI:
        <a
          href="https://openai.com/policies/service-terms/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-500 hover:underline ml-1"
        >
          OpenAI Haftungsausschluss
        </a>
        .
      </span>,
      <span key="de-kontaktinformationen">
        <strong>Kontaktinformationen:</strong>
        <br />
        Diego de Miguel
        <br />
        Sillemstraße 43
        <br />
        Hamburg, 20257
        <br />
        E-Mail:{" "}
        <a
          href="mailto:diedemiguel@gmail.com"
          className="text-blue-500 hover:underline"
        >
          diedemiguel@gmail.com
        </a>
        <br />
      </span>,
    ],
    homeLink: "Home",
    language: "Sprache",
    english: "Englisch",
    german: "Deutsch",
  },
};

export default translations;
